### ISSUE TITLE
[iOS] How to localize?

### ISSUE THREAD

**Issue by defuncart** [jachzen/cunning_document_scanner#10]
Hi 👋 , thanks for creating this package. For iOS, [VNDocumentCameraViewController ](https://developer.apple.com/documentation/visionkit/vndocumentcameraviewcontroller) is used. I assume that Apple have automatically localized this controller? In the README it can be seen that although the device language is DE, EN is displayed in the controller. This I can also reproduce using example app, even adding `flutter_localizations` and hardcoding the locale does not change anything.

**Comment by chrisDupuis** [comment]
see flutter localized on ios
https://docs.flutter.dev/development/accessibility-and-localization/internationalization

set in main
 localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('fr', ''), // French, no country code
      ],

set Info.plist
<key>CFBundleLocalizations</key>
	<array>
		<string>fr</string>
	</array>

**Comment by defuncart** [comment]
Apologies, this seems to have been an error on my side, in a separate project, everything works as expected.
