### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses' when some other plugin that uses OpenCV is added

### ISSUE THREAD

**Issue by SmearyQuill** [jachzen/cunning_document_scanner#11]
Hi, so far your plugin works great thank you very much. But now i faced and issue when i was about to add a button to filter the image.

First i added a opencv plugin like the one available here: https://pub.dev/packages/opencv

But when i tried to run the app a get the next error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.opencv.BuildConfig found in modules jetified-opencv-4.1.0-runtime (com.quickbirdstudios:opencv:4.1.0) and jetified-opencv-4.1.0-runtime (com.websitebeaver:opencv:4.1.0)
[...]

And the error output just list a lot of classes like the example above

I did some research but from what i can tell the problem is the opencv implementation that this plugin uses is "com.websitebeaver:opencv:4.1.0" and when another plugin that uses opencv  is added the duplicated classes error happens because they use the "com.quickbirdstudios:opencv:4.1.0" implementation or some other version.

Is there a way to fix this issue?

**Comment by jachzen** [comment]
Propbably you can exclude the one or the Other opencv library in Android. Check your gradle Files.

**Comment by Niketgoriya** [comment]
how do i modified this package to use com.quickbirdstudios:opencv:4.3.0  ?
