### ISSUE TITLE
Crash on multi image cancellation

### ISSUE THREAD

**Issue by CodeRedDev** [jachzen/cunning_document_scanner#14]
When clicking on the add picture button after taking a first picture and then navigating back to confirm the selection of only one picture the demo app will crash.

I have tested the same use case on the `WebsiteBeaver/android-document-scanner` Demo App and could not recreate the behaviour.

Maybe an update of the dependency could fix the problem 🤷 

Also it would be great to have some customization options like if you really want the option of multiple pictures. But that is probably worth another issue.

**Comment by aimanaqib** [comment]
I am getting the same crash as well for version 1.1.2. Is this already updated to the current version?

**Comment by vicajilau** [comment]
This type of bug should have been resolved in the latest version 1.1.4. If not, we would appreciate it if you could reopen the defect and give us some more information. Thank you very much for using cuning_document_scanner 😃
