### ISSUE TITLE
Iphone 13 and above black image

### ISSUE THREAD

**Issue by Sergiobi9** [jachzen/cunning_document_scanner#19]
Hello,

I'm using this library to scan documents. Which is awesome! But in the latest iPhone 13 and 14 when I take a photo and scan I receive a black image instead. I mean I see the photo while cropping but when I finish, the photo is black.

I don't know if you are facing this issue, you need to test it on a real iPhone 13 or 14 device.

**Comment by jachzen** [comment]
I will try to reproduce the issue asap.

**Comment by vicajilau** [comment]
This defect has been resolved and is not reproduced in version 1.1.4. Thank you for using cunning_document_scanner and we invite you to reopen it with more information in case it is reproduced again.
