### ISSUE TITLE
Android not auto-cropping

### ISSUE THREAD

**Issue by atnegrete** [jachzen/cunning_document_scanner#20]
Looks like identical to #7 

I've tried different documents, no luck getting it to auto-crop. I'm using the latest 1.1.2 version.

Any help appreciated, thanks!

**Comment by CikaTom** [comment]
Any update on this?

**Comment by vicajilau** [comment]
This feature has been added in version 1.1.4. Thank you for using cunning_document_scanner.

**Comment by maxfornacon** [comment]
I tested version 1.1.4 and in many situations still no sheet was automatically detected or the quality of the detected border was not really good compared to other scanning apps.

 I tested it in practical (not perfect) lighting conditions and compared it with other scanner apps.

**Comment by vicajilau** [comment]
Might you provide us more information about it @maxfornacon? For example a video? Having device model or Android version will help us a lot. Thanks

**Comment by Masaa44** [comment]
Same error here, there is no detection of the document on android 14 with cunning_document v 1.1.4
It work fine on IOS

**Comment by Varun9729** [comment]
> Same error here, there is no detection of the document on android 14 with cunning_document v 1.1.4 It work fine on IOS

Did you find a fix for this? 
I have the same issue, auto croppping does not work on Android, but works fine on IOS devices

**Comment by Varun9729** [comment]
Any update on this issue? There is no auto-detection on Android and I still have to manually crop the scan.

**Comment by maxfornacon** [comment]
It happens to work on very rare occasions. I guess lighting and contrast of page to underground must be perfect. Detection rate on iOS is way better.

**Comment by martinogarrizzo5** [comment]
I hope the developer will improve the feature also on Android! I really need it.
Please continue to mantain the library!

**Comment by vicajilau** [comment]
We greatly appreciate your patience and support in resolving this bug. A number of changes have been made to the master branch of the project. Could some of you @maxfornacon, @Varun9729, @martinogarrizzo5, @Masaa44, @atnegrete or @CikaTom test it before releasing a version and let us know if the sample project gives you the same result? It is worth noting that one of the changes is that now that more parameters are accepted, parameters with names are used

**Comment by vicajilau** [comment]
Finally the Android implementation has been rewritten using ML Kit and the auto-crop option will no longer be optional and is available to everyone in the next release. Thank you very much for your patience.
