### ISSUE TITLE
multi photo

### ISSUE THREAD

**Issue by SamadDev** [jachzen/cunning_document_scanner#22]
how to not let the user take more than one photo and choose this photo automatically after closed

**Comment by Tho100** [comment]
I don't think that's yet possible. We'll wait until the creator allow this feature.

**Comment by vicajilau** [comment]
As @Tho100 points out this is not easily possible. On iOS this functionality is implemented through the native [VNDocumentCameraViewController](https://developer.apple.com/documentation/visionkit/vndocumentcameraviewcontroller) feature which does not allow this functionality. If you only want to scan a single image or document I would easily suggest to do it through the camera and not through a scanner.
