### ISSUE TITLE
PermanentlyDenied on iOS 16

### ISSUE THREAD

**Issue by vicajilau** [jachzen/cunning_document_scanner#26]
As you can see in the attached image, a device with permissions to access the camera is returning a permissions denied error. 

This causes an error on the next Pull Request https://github.com/jachzen/cunning_document_scanner/pull/25

<img width="1064" alt="image" src="https://github.com/jachzen/cunning_document_scanner/assets/34163765/ddc85728-43de-4f36-97fd-e3e540856a97">

**Comment by vicajilau** [comment]
It has been resolved on the same Pull Request updating permission_handler dependency

**Comment by jachzen** [comment]
Done
