### ISSUE TITLE
tha package size is too big

### ISSUE THREAD

**Issue by yargm** [jachzen/cunning_document_scanner#3]
I was surprised when after developing the tool I needed, I generated the apk and it weighed more than 140 MB having only this library

**Comment by mminhlequang** [comment]
size of example package is 350MB

**Comment by jachzen** [comment]
the resulting apks should be quite small. check version 1.1.0. Example with debu info 39mb

**Comment by mminhlequang** [comment]
Oh you already changed lib for android, let's see

**Comment by vaartatechnologies** [comment]
Me too facing the same problem. Using version 1.1.2.

Before using this package .aab size was 47 MBs, but after it was 103 MBs.
