### ISSUE TITLE
Permission not granted on iOS

### ISSUE THREAD

**Issue by maxfornacon** [jachzen/cunning_document_scanner#35]
As far as I understand the package should ask for camera permission as soon as the getPictures()-method is called.

It seems to not work in 1.1.4 on iOS 17.1.1 (iPhone 13). It just throws `Unhandled Exception: Exception: Permission not granted`.

Couldn't test it on Android yet.

**Comment by maxfornacon** [comment]
I forgot to edit the Podfile.

**Comment by FedeRotoli** [comment]
How do you solved this? Shows me the same error also in the latest version (1.1.4)

**Comment by maxfornacon** [comment]
> How do you solved this? Shows me the same error also in the latest version (1.1.4)

I hadn't done Step 2 of the "Getting Started - iOS" section of the readme. Just be sure you followed the instructions.
