### ISSUE TITLE
Scanning documents from gallery

### ISSUE THREAD

**Issue by LynxLynxx** [jachzen/cunning_document_scanner#36]
Hi, do you plan to scan documents comming from gallery?

**Comment by vicajilau** [comment]
We are currently working on adding support for PDF generation and page number limitation. Adding the gallery is something that is on our roadmap but will take some time to implement. I suggest you keep an eye on cunning_document_scanner in the future.

**Comment by vicajilau** [comment]
A [Pull Request](https://github.com/jachzen/cunning_document_scanner/pull/51) has been added following this implementation @CodeRedDev

**Comment by jachzen** [comment]
Added in 1.2.1. For iOS we need to consider to go away from VNDocumentCameraViewController

**Comment by loveoverflowdev** [comment]
> Added in 1.2.1. For iOS we need to consider to go away from VNDocumentCameraViewController

Maybe we don't need.
Please follow some method like that, thank you:

https://stackoverflow.com/questions/62373844/using-vision-to-scan-images-from-photo-library
