### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Intent?

### ISSUE THREAD

**Issue by HeynSekk** [jachzen/cunning_document_scanner#4]
I run debug apk of the example project provided in this repo. It show this error.

`[        ] e:
/home/heinsek/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cunning_document_scanner-1.0.2/android/s
rc/main/kotlin/biz/cunning/cunning_document_scanner/CunningDocumentScannerPlugin.kt: (110, 29): Only safe (?.) or
non-null asserted (!!.) calls are allowed on a nullable receiver of type Intent?
[        ] e:
/home/heinsek/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cunning_document_scanner-1.0.2/android/s
rc/main/kotlin/biz/cunning/cunning_document_scanner/CunningDocumentScannerPlugin.kt: (112, 36): Only safe (?.) or
non-null asserted (!!.) calls are allowed on a nullable receiver of type Intent?
[        ] e:
/home/heinsek/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cunning_document_scanner-1.0.2/android/s
rc/main/kotlin/biz/cunning/cunning_document_scanner/CunningDocumentScannerPlugin.kt: (113, 45): Only safe (?.) or
non-null asserted (!!.) calls are allowed on a nullable receiver of type Intent?
[        ] e:
/home/heinsek/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cunning_document_scanner-1.0.2/android/s
rc/main/kotlin/biz/cunning/cunning_document_scanner/CunningDocumentScannerPlugin.kt: (117, 45): Only safe (?.) or
non-null asserted (!!.) calls are allowed on a nullable receiver of type Intent?
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':cunning_document_scanner:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 55s
[ +435 ms] Running Gradle task 'assembleDebug'... (completed in 56.7s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1`

Then, I added the plugin to my original project that I'm working on currently, it show the same error.

Is there any temporary workaround? 

Flutter doctor 
`[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 20.04.4 LTS 5.13.0-52-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (3 available)
`

Anyone else can run debug apk with the plugin? If yes, could you please provide a release APK that use the plugin bc I would like to see how the scanning experience look like.

**Comment by bdlindsay** [comment]
I've submitted a PR to at least get this compiling.
You can point to the fork for now.
https://github.com/bdlindsay/cunning_document_scanner

**Comment by jachzen** [comment]
new Version published 1.1.0
