### ISSUE TITLE
Release an update with AGP 8 support

### ISSUE THREAD

**Issue by vbuberen** [jachzen/cunning_document_scanner#46]
Would like to ask to release another update of the plugin to support projects which migrate or already migrated to Android Gradle Plugin 8.

I see that [there is a commit](https://github.com/jachzen/cunning_document_scanner/commit/a2b99404445bcf29df92f8a79c3a9e6d7474a4f3) with added `namespace` property and I can point to commit in pubspec declaration without problems, but I believe it would be beneficial for most users to have this commit in one of published versions, especially as more plugins already moved that way (for example, Flutterfire plugins back in October: https://github.com/firebase/flutterfire/blob/master/CHANGELOG.md#cloud_firestore---v4100)

Thanks in advance

**Comment by martinogarrizzo5** [comment]
+1
