### ISSUE TITLE
Possible exception on low-end devices with Android

### ISSUE THREAD

**Issue by martinogarrizzo5** [jachzen/cunning_document_scanner#49]
Hi there,

I recently noticed that the library has been updated with a new ml kit document scanner, and I must say I loved it. However, I came across some documentation on Google's website at [https://developers.google.com/ml-kit/vision/doc-scanner/android?hl=en](https://developers.google.com/ml-kit/vision/doc-scanner/android?hl=en), which states that devices with less than 1.7GB of RAM cannot run the scanner and will receive an exception error. Is the exception handled by the library? As there are still people using low-end devices, I want to avoid any unexpected crashes caused by this issue.

Thank you in advance for your response.

Best regards,
Martin

**Comment by jachzen** [comment]
You are right. I will implement a fallback. Maybe a version without autocropping as this was not working so good with opencv. Otherwise the plugin has all the opencv dependencies which increases the package size.

**Comment by CodeRedDev** [comment]
For a fallback that supports autocropping this could also be accomplished by a minimized OpenCV build in combination with Dart FFI. Quality of autocropping will be the same as before MLKit (problems with low contrast and image anomalies).

Error handling becomes a bit hacky though.

I think, if basic cropping can be accomplished without OpenCV it's the better fallback.

**Comment by jachzen** [comment]
Check Version 1.21. I added a fallback with simple manuel cropping
