### ISSUE TITLE
The auto-cropper doesn't work at all after upgrading to 1.2.1

### ISSUE THREAD

**Issue by HandwerSTD** [jachzen/cunning_document_scanner#54]
As mentioned in the title, even on high-contrast pictures.

This is how 1.2.1 behaves:
![Screenshot_20240316_155934_com tianzhu purlaw](https://github.com/jachzen/cunning_document_scanner/assets/37949764/980ff781-bfa7-4779-84db-9ad4b211ef52)

This is how 1.1.4 behaves:
![Screenshot_20240316_161442_com tianzhu purlaw](https://github.com/jachzen/cunning_document_scanner/assets/37949764/7eb65303-2089-4017-8c40-6747801a7f64)

Device: HUAWEI P60
System: HarmonyOS 4.0.0.200, Android 12 (S), without GMS so probably no MLKit

**Comment by jachzen** [comment]
On devices not suitable to run ml Kit document scanner we dropped the autocrop in favour for package size. It wasn't working very good anyway and for most devices the ml Kit works and is much much better.
If you Like the old Implementation just go back to Version < 1.2
