### ISSUE TITLE
Not auto cropping on android

### ISSUE THREAD

**Issue by ahmadrana24** [jachzen/cunning_document_scanner#7]
The package is not auto cropping on android/

**Comment by asimappdev** [comment]
@jachzen Working really well on iOS but not on Android. Please check out the following android scanner library looks identical to what you did in iOS:
https://github.com/SDA-SE/document-scanner-android

**Comment by jachzen** [comment]
OK. I will give it a try. Have you checked the demo on Android. Is it working nicely?

**Comment by asimappdev** [comment]
We have but it is not auto cropping and after taking the picture the manual edge selection is also not working as it works on iOS.

**Comment by asimappdev** [comment]
and it also auto-rotates the image on its own.

**Comment by jachzen** [comment]
ok this works much better. But i will use the original one https://github.com/WebsiteBeaver/android-document-scanner not the forked one - i checked the code and the difference is just the packagenaming

**Comment by jachzen** [comment]
See branch [feature/androidWebsiteBeaverScanner](https://github.com/jachzen/cunning_document_scanner/tree/feature/androidWebsiteBeaverScanner) 
Please test it and review. if it is ok i will upload a new version on pub.dev

**Comment by asimappdev** [comment]
Sure, will test it today and let you know the feedback. Thank you so much for all your help.

**Comment by jachzen** [comment]
new version available under 1.1.0
