### ISSUE TITLE
The Buttons Disappeared

### ISSUE THREAD

**Issue by MhdYhyaAlshaki** [jachzen/cunning_document_scanner#8]
After setting the file borders, the buttons behind the image disappear. This condition only occurs when the image is changed to 19:6 or full screen This is a screenshot [example](https://drive.google.com/drive/folders/1x80glkbTQHZZhKmcSdt1ilws096Td-uz?usp=sharing)

**Comment by jachzen** [comment]
What do you mean exactly by setting Fileborder?
