### ISSUE TITLE
Same temp file returned when calling getPictures() multiple times on iOS

### ISSUE THREAD

**Issue by ckovamees** [jachzen/cunning_document_scanner#9]
Thanks for a great plugin! 💯 

I just updated to iOS 16.1 on an iPad mini and is encountering this problem on iOS, it works fine on Android 13 (Pixel 6).

A call to (with one picture only):
`final files = await CunningDocumentScanner.getPictures();`
Returns a filename like below.

### iOS 16.1
/var/mobile/Containers/Data/Application/<digitsanddashes>/Documents/**tmp-document-0.png**
This is the same value every time I call `getPictures()`.

### Android 13
/storage/emulated/0/Android/data/<myapp>/files/Pictures/DOCUMENT_SCAN_0_20221029_1036401226442687912810439.jpg
Which gives a different file every time `getPictures()` is called.

I can't say this is new behavior or not with iOS 16.1. I might have missed it previously, but is experiencing it now.

While at it... (really different issue) - they return different images. PNG on iOS and JPG on Android. (?)

**Comment by jachzen** [comment]
I think the files should be moved to another Location anyway. It is only a temporary File. But there was another request concerning this. So i will Look into it and let you know.
The File Format ist the one i get from the used library Implementation. I need to Check if it is configurable. But good Point.

**Comment by jachzen** [comment]
check version 1.1.2. which addressed the filename issue
